# Generated by Django 4.1.2 on 2023-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Childs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12)),
                ('name', models.TextField(blank=True, null=True)),
                ('id_group', models.CharField(max_length=15)),
                ('id_org', models.CharField(max_length=15)),
                ('registered', models.BooleanField(default=False)),
                ('child_image', models.TextField(default='', null=True)),
                ('id_face', models.TextField(default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.CharField(max_length=15)),
                ('id_org', models.CharField(default='00000', max_length=15)),
                ('group_name', models.TextField(blank=True, null=True)),
                ('group_age', models.TextField(blank=True, null=True)),
                ('group_count', models.CharField(max_length=15, null=True)),
                ('username', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_org', models.CharField(max_length=15)),
                ('org_name', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_org', models.CharField(max_length=15)),
                ('name', models.TextField(blank=True, null=True)),
                ('is_adm_org', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.CharField(max_length=15)),
                ('id_org', models.CharField(max_length=15)),
                ('iin', models.CharField(max_length=15)),
                ('status', models.CharField(default='0', max_length=15)),
                ('datestatus', models.DateField(null=True)),
                ('timestatus', models.TimeField(null=True)),
            ],
        ),
    ]
