# Generated by Django 4.1.2 on 2023-01-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_count',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
