# Generated by Django 4.1.2 on 2023-01-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0002_alter_groups_group_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='group_count',
        ),
    ]
