# Generated by Django 4.1.2 on 2023-01-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0003_remove_groups_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_count',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
