# Generated by Django 4.1.2 on 2023-01-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0004_groups_group_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='is_adm_org',
        ),
    ]
