# Generated by Django 4.1.2 on 2023-01-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0005_remove_profileuser_is_adm_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='is_adm_org',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
