# Generated by Django 4.1.2 on 2023-01-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0006_profileuser_is_adm_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_count',
            field=models.IntegerField(default=0),
        ),
    ]
