# Generated by Django 4.1.2 on 2023-01-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0007_alter_groups_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
