# Generated by Django 4.1.2 on 2023-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0008_groups_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='childs',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
