# Generated by Django 4.1.2 on 2023-01-20 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0015_alter_visits_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 20, 22, 46, 27, 180980), null=None),
        ),
    ]
