# Generated by Django 4.1.2 on 2023-01-20 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0016_profileuser_is_delete_alter_visits_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 20, 22, 46, 31, 587090), null=None),
        ),
    ]
