# Generated by Django 4.1.2 on 2023-01-20 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0018_rename_gernder_childs_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 21, 0, 10, 52, 536243), null=None),
        ),
    ]
