# Generated by Django 4.1.2 on 2023-01-20 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0019_alter_visits_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childs',
            name='create_date',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 21, 0, 11, 58, 258601), null=None),
        ),
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 21, 0, 11, 58, 305340), null=None),
        ),
    ]
