# Generated by Django 4.1.2 on 2023-01-20 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0020_alter_childs_create_date_alter_visits_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childs',
            name='create_date',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 21, 0, 12, 7, 712048), null=None),
        ),
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 21, 0, 12, 7, 743297), null=None),
        ),
    ]
