# Generated by Django 4.1.2 on 2023-01-26 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0023_alter_childs_create_date_alter_visits_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='childs',
            name='create_date',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 26, 17, 34, 48, 140321), null=None),
        ),
    ]
