# Generated by Django 4.1.2 on 2023-01-29 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0023_visits_username_alter_childs_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='imageURL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childs',
            name='create_date',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 29, 17, 41, 16, 653198), null=None),
        ),
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 29, 17, 41, 16, 700321), null=None),
        ),
    ]
