# Generated by Django 4.1.2 on 2023-01-29 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0024_visits_imageurl_alter_childs_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visits',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='childs',
            name='create_date',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 29, 17, 59, 50, 918779), null=None),
        ),
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 29, 17, 59, 50, 950029), null=None),
        ),
    ]
