# Generated by Django 4.1.2 on 2023-01-30 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0026_remove_childs_child_image_childs_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='is_pass_chek',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='childs',
            name='create_date',
            field=models.DateField(blank=None, default=datetime.datetime(2023, 1, 30, 17, 2, 50, 559462), null=None),
        ),
        migrations.AlterField(
            model_name='visits',
            name='create_date',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2023, 1, 30, 17, 2, 50, 590712), null=None),
        ),
    ]
