# Generated by Django 4.1.2 on 2023-02-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0027_profileuser_is_pass_chek_alter_childs_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.TextField(default='', max_length=12)),
                ('org_name', models.TextField(blank=True, null=True)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('phonenumber', models.TextField(blank=True, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('datestatus', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visits',
            name='create_date',
        ),
        migrations.AddField(
            model_name='organizations',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='bin',
            field=models.TextField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='organizations',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='fullname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='phonenumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childs',
            name='create_date',
            field=models.DateField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='create_date',
            field=models.DateField(null=True),
        ),
    ]
