# Generated by Django 4.1.2 on 2023-02-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0028_neworganizations_remove_visits_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('id_parent', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.CharField(max_length=15)),
                ('id_child', models.CharField(max_length=15)),
            ],
        ),
    ]
