# Generated by Django 4.1.2 on 2023-02-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0029_regions_suborganizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regions',
            name='id_parent',
            field=models.BigIntegerField(default=0),
        ),
    ]
