# Generated by Django 4.1.2 on 2023-02-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0030_alter_regions_id_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworganizations',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neworganizations',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
    ]
