# Generated by Django 4.1.2 on 2023-02-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0031_neworganizations_latitude_neworganizations_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='worktimestart',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='worktimestop',
            field=models.TimeField(null=True),
        ),
    ]
