# Generated by Django 4.1.2 on 2023-02-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0032_organizations_worktimestart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworganizations',
            name='id_obl',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neworganizations',
            name='id_region',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neworganizations',
            name='status',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
