# Generated by Django 4.1.2 on 2023-02-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0033_neworganizations_id_obl_neworganizations_id_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
