# Generated by Django 4.1.2 on 2023-02-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0035_childs_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
