# Generated by Django 4.1.2 on 2023-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0036_alter_groups_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworganizations',
            name='count_place',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neworganizations',
            name='type_org',
            field=models.CharField(default='pr', max_length=2),
        ),
        migrations.AddField(
            model_name='regions',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regions',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
    ]
