# Generated by Django 4.1.2 on 2023-03-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0037_neworganizations_count_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
