# Generated by Django 4.1.2 on 2023-03-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0038_alter_groups_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='category',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
