# Generated by Django 4.1.2 on 2023-04-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0041_organizations_count_place_organizations_name_obl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizations',
            name='name_obl',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='name_region',
        ),
        migrations.AlterField(
            model_name='organizations',
            name='type_org',
            field=models.CharField(default='pr', max_length=3),
        ),
    ]
