# Generated by Django 4.1.2 on 2023-04-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0042_remove_organizations_name_obl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
