# Generated by Django 4.1.2 on 2023-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0043_visits_edited'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekendDate', models.DateField(null=True)),
                ('name', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
            },
        ),
    ]
