# Generated by Django 4.1.2 on 2023-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0045_alter_suborganizations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childs',
            name='id_face512',
            field=models.TextField(default='', null=True),
        ),
    ]
