# Generated by Django 4.1.2 on 2023-05-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0048_neworganizations_type_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptors',
            name='id_face1024',
            field=models.TextField(default='', null=True),
        ),
    ]
