# Generated by Django 4.1.2 on 2023-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0050_descriptors_id_face128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworganizations',
            name='type_org',
            field=models.CharField(blank=True, default='gos', max_length=3, null=True),
        ),
    ]
