# Generated by Django 4.1.2 on 2023-05-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0051_alter_neworganizations_type_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ecolog', models.CharField(blank=True, default='normal', max_length=6, null=True)),
                ('price', models.BigIntegerField(default=0)),
                ('obl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceback.regions')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Цены обслуживания',
            },
        ),
    ]
