# Generated by Django 4.1.2 on 2023-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0052_priceservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceservice',
            name='type_city',
            field=models.CharField(blank=True, default='gor', max_length=4, null=True),
        ),
    ]
