# Generated by Django 4.1.2 on 2023-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0053_priceservice_type_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceservice',
            name='category',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
