# Generated by Django 4.1.2 on 2023-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0054_priceservice_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='childs',
            name='category',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
