# Generated by Django 4.1.2 on 2023-07-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0055_childs_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiSpoof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.TextField(default='', null=True)),
                ('var2', models.TextField(default='', null=True)),
                ('imagename', models.TextField(blank=True, null=True)),
                ('res', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
