# Generated by Django 4.1.2 on 2023-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0056_antispoof'),
    ]

    operations = [
        migrations.AddField(
            model_name='antispoof',
            name='argmax1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='antispoof',
            name='argmax2',
            field=models.TextField(default='', null=True),
        ),
    ]
