# Generated by Django 4.1.2 on 2023-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0057_antispoof_argmax1_antispoof_argmax2'),
    ]

    operations = [
        migrations.AddField(
            model_name='antispoof',
            name='argmax',
            field=models.TextField(blank=True, null=True),
        ),
    ]
