# Generated by Django 4.1.2 on 2023-08-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0058_antispoof_argmax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childs',
            name='id_group',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='childs',
            name='id_org',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='childs',
            name='iin',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='childs',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptors',
            name='iin',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='visits',
            name='id_group',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='visits',
            name='id_org',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='visits',
            name='iin',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
