# Generated by Django 4.1.2 on 2023-08-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0059_alter_childs_id_group_alter_childs_id_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='id_group',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='groups',
            name='id_org',
            field=models.CharField(db_index=True, default='00000', max_length=15),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='bin',
            field=models.TextField(db_index=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='fullname',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='id_org',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='id_org',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='datestatus',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
