# Generated by Django 4.1.2 on 2023-08-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0060_alter_groups_id_group_alter_groups_id_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='hostname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
