# Generated by Django 4.1.2 on 2023-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0063_itogbyday_itogbymonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeCountByIIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(db_index=True, max_length=12)),
                ('create_date', models.DateField(blank=None, null=True)),
                ('confidence', models.FloatField(default=0, null=True)),
                ('count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
