# Generated by Django 4.1.2 on 2023-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0064_fakecountbyiin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AntiSpoof',
        ),
        migrations.RemoveField(
            model_name='childs',
            name='id_face',
        ),
        migrations.RemoveField(
            model_name='childs',
            name='id_face512',
        ),
        migrations.AddField(
            model_name='childs',
            name='clone',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='visits',
            name='srvcolumn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
