# Generated by Django 4.1.2 on 2023-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0065_delete_antispoof_remove_childs_id_face_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_org', models.CharField(db_index=True, max_length=15)),
                ('id_group', models.CharField(db_index=True, max_length=15)),
                ('iin', models.CharField(db_index=True, max_length=15)),
                ('date', models.DateField(db_index=True, null=True)),
                ('timestatus', models.TimeField(null=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('date_dir', models.DateField(db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'История ребенка',
                'verbose_name_plural': 'Истории ребенка',
            },
        ),
    ]
