# Generated by Django 4.1.2 on 2023-09-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0066_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='fakeresult',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
