# Generated by Django 4.1.2 on 2023-09-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0067_visits_fakeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(db_index=True, max_length=12)),
                ('chatid', models.BigIntegerField(null=True)),
            ],
        ),
    ]
