# Generated by Django 4.1.2 on 2023-10-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceback', '0068_telegramdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits_faceme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.CharField(db_index=True, max_length=15)),
                ('id_org', models.CharField(db_index=True, max_length=15)),
                ('iin', models.CharField(db_index=True, max_length=15)),
                ('status', models.CharField(default='0', max_length=15)),
                ('username', models.TextField(blank=True, null=True)),
                ('datestatus', models.DateField(db_index=True, null=True)),
                ('timestatus', models.TimeField(null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('srvcolumn', models.TextField(blank=True, null=True)),
                ('edited', models.BooleanField(default=False)),
                ('fakeresult', models.FloatField(blank=True, default=1, null=True)),
            ],
        ),
    ]
